spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
      connection-init-sql: RUNSCRIPT FROM 'classpath:/data-h2.sql';RUNSCRIPT FROM 'classpath:/data-h3.sql'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

